require 'rake/builder'

Rake::Builder.new do |builder|
  builder.target = 'people'
  builder.architecture = 'x86_64'
  builder.installable_headers = ['../../include/active_record']
  builder.objects_path = '.'
  builder.include_paths = [
    '.',
    '../../include',
    '../../include/postgresql',
    '../../include/postgresql/server'
  ]
  builder.library_paths = ['../..']
  builder.library_dependencies = [
    'boost_date_time',
    'active_record_x86_64',
    'sqlite3'
  ]
end
